/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JDesktopPane;

/**
 *
 * @author User
 */
public class HomeFrame extends javax.swing.JInternalFrame {
    private JDesktopPane desktop;

    /**
     * Creates new form HomeFrame
     */

    public HomeFrame(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPatients = new javax.swing.JButton();
        btnRdv = new javax.swing.JButton();
        btnGraph = new javax.swing.JButton();
        btnMedecins = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(21, 31, 40));

        btnPatients.setBackground(new java.awt.Color(237, 237, 237));
        btnPatients.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPatients.setText("Patients");
        btnPatients.setBorderPainted(false);
        btnPatients.setContentAreaFilled(false);
        btnPatients.setFocusPainted(false);
        btnPatients.setOpaque(true);
        btnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsActionPerformed(evt);
            }
        });

        btnRdv.setBackground(new java.awt.Color(237, 237, 237));
        btnRdv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRdv.setText("Rendez-vous");
        btnRdv.setBorderPainted(false);
        btnRdv.setContentAreaFilled(false);
        btnRdv.setFocusPainted(false);
        btnRdv.setOpaque(true);
        btnRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRdvActionPerformed(evt);
            }
        });

        btnGraph.setBackground(new java.awt.Color(237, 237, 237));
        btnGraph.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGraph.setForeground(new java.awt.Color(198, 40, 40));
        btnGraph.setText("Graphique");
        btnGraph.setBorderPainted(false);
        btnGraph.setContentAreaFilled(false);
        btnGraph.setFocusPainted(false);
        btnGraph.setOpaque(true);
        btnGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphActionPerformed(evt);
            }
        });

        btnMedecins.setBackground(new java.awt.Color(237, 237, 237));
        btnMedecins.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMedecins.setForeground(new java.awt.Color(198, 40, 40));
        btnMedecins.setText("Medecins");
        btnMedecins.setBorderPainted(false);
        btnMedecins.setContentAreaFilled(false);
        btnMedecins.setFocusPainted(false);
        btnMedecins.setOpaque(true);
        btnMedecins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedecinsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRdv, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(btnPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedecins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btnPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnMedecins, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconmed.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(237, 237, 237));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(198, 40, 40));
        jLabel2.setText("Centre Medical");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        openPatients();
    }//GEN-LAST:event_btnPatientsActionPerformed

    private void btnRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRdvActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        openRdvs();
    }//GEN-LAST:event_btnRdvActionPerformed

    private void btnGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        openGraphs();
    }//GEN-LAST:event_btnGraphActionPerformed

    private void btnMedecinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedecinsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        openMedecins();
    }//GEN-LAST:event_btnMedecinsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraph;
    private javax.swing.JButton btnMedecins;
    private javax.swing.JButton btnPatients;
    private javax.swing.JButton btnRdv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void openPatients() {
        desktop.removeAll();
        desktop.repaint();

        Patients pf = new Patients();

        pf.setClosable(false);
        pf.setResizable(false);
        pf.setMaximizable(false);
        pf.setIconifiable(false);
        pf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) pf.getUI()).setNorthPane(null);
        

        desktop.add(pf);
        pf.setVisible(true);

        try {
            pf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void openMedecins() {
        desktop.removeAll();
        desktop.repaint();

        Medecins mf = new Medecins();

        mf.setClosable(false);
        mf.setResizable(false);
        mf.setMaximizable(false);
        mf.setIconifiable(false);
        mf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) mf.getUI()).setNorthPane(null);
        

        desktop.add(mf);
        mf.setVisible(true);

        try {
            mf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void openRdvs() {
        desktop.removeAll();
        desktop.repaint();

        Rdvs rf = new Rdvs();

        rf.setClosable(false);
        rf.setResizable(false);
        rf.setMaximizable(false);
        rf.setIconifiable(false);
        rf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) rf.getUI()).setNorthPane(null);
        

        desktop.add(rf);
        rf.setVisible(true);

        try {
            rf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void openGraphs() {
        desktop.removeAll();
        desktop.repaint();

        Graph gf = new Graph();

        gf.setClosable(false);
        gf.setResizable(false);
        gf.setMaximizable(false);
        gf.setIconifiable(false);
        gf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) gf.getUI()).setNorthPane(null);
        

        desktop.add(gf);
        gf.setVisible(true);

        try {
            gf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
