/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        openHomeFrame();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnPt = new javax.swing.JButton();
        btnMd = new javax.swing.JButton();
        btnRdv = new javax.swing.JButton();
        btnGraph = new javax.swing.JButton();
        btnCl = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jDesktopPane2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(21, 31, 40));

        jLabel3.setBackground(new java.awt.Color(21, 31, 40));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 237, 237));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconsmall.png"))); // NOI18N
        jLabel3.setText("Centre Medical");

        btnHome.setBackground(new java.awt.Color(40, 31, 21));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home (2).png"))); // NOI18N
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusPainted(false);
        btnHome.setOpaque(true);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPt.setBackground(new java.awt.Color(40, 31, 21));
        btnPt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/patient.png"))); // NOI18N
        btnPt.setBorderPainted(false);
        btnPt.setContentAreaFilled(false);
        btnPt.setFocusPainted(false);
        btnPt.setOpaque(true);
        btnPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPtActionPerformed(evt);
            }
        });

        btnMd.setBackground(new java.awt.Color(40, 31, 21));
        btnMd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/medcin.png"))); // NOI18N
        btnMd.setBorderPainted(false);
        btnMd.setContentAreaFilled(false);
        btnMd.setFocusPainted(false);
        btnMd.setOpaque(true);
        btnMd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMdActionPerformed(evt);
            }
        });

        btnRdv.setBackground(new java.awt.Color(40, 31, 21));
        btnRdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rdv.png"))); // NOI18N
        btnRdv.setBorderPainted(false);
        btnRdv.setContentAreaFilled(false);
        btnRdv.setFocusPainted(false);
        btnRdv.setOpaque(true);
        btnRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRdvActionPerformed(evt);
            }
        });

        btnGraph.setBackground(new java.awt.Color(40, 31, 21));
        btnGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/graph.png"))); // NOI18N
        btnGraph.setBorderPainted(false);
        btnGraph.setContentAreaFilled(false);
        btnGraph.setFocusPainted(false);
        btnGraph.setOpaque(true);
        btnGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphActionPerformed(evt);
            }
        });

        btnCl.setBackground(new java.awt.Color(40, 31, 21));
        btnCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close.png"))); // NOI18N
        btnCl.setBorderPainted(false);
        btnCl.setContentAreaFilled(false);
        btnCl.setFocusPainted(false);
        btnCl.setOpaque(true);
        btnCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClActionPerformed(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(40, 31, 21));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minimize (1).png"))); // NOI18N
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setFocusPainted(false);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnPt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGraph)
                    .addComponent(btnRdv)
                    .addComponent(btnMd)
                    .addComponent(btnPt)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        openHomeFrame();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPtActionPerformed
        // TODO add your handling code here:
        openPatients();
    }//GEN-LAST:event_btnPtActionPerformed

    private void btnMdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMdActionPerformed
        // TODO add your handling code here:
        openMedecins();
    }//GEN-LAST:event_btnMdActionPerformed

    private void btnRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRdvActionPerformed
        // TODO add your handling code here:
        openRdvs();
    }//GEN-LAST:event_btnRdvActionPerformed

    private void btnGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphActionPerformed
        // TODO add your handling code here:
        openGraphs();
    }//GEN-LAST:event_btnGraphActionPerformed

    private void btnClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnClActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // TODO add your handling code here:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinActionPerformed
    
    
    
    private void openPatients() {
        Patients pf = new Patients();

        pf.setClosable(false);
        pf.setResizable(false);
        pf.setMaximizable(false);
        pf.setIconifiable(false);
        pf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) pf.getUI()).setNorthPane(null);
        

        jDesktopPane2.add(pf);
        pf.setVisible(true);

        try {
            pf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void openMedecins() {
        Medecins mf = new Medecins();

        mf.setClosable(false);
        mf.setResizable(false);
        mf.setMaximizable(false);
        mf.setIconifiable(false);
        mf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) mf.getUI()).setNorthPane(null);
        

        jDesktopPane2.add(mf);
        mf.setVisible(true);

        try {
            mf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void openRdvs() {
        Rdvs rf = new Rdvs();

        rf.setClosable(false);
        rf.setResizable(false);
        rf.setMaximizable(false);
        rf.setIconifiable(false);
        rf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) rf.getUI()).setNorthPane(null);
        

        jDesktopPane2.add(rf);
        rf.setVisible(true);

        try {
            rf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void openGraphs() {
        Graph gf = new Graph();

        gf.setClosable(false);
        gf.setResizable(false);
        gf.setMaximizable(false);
        gf.setIconifiable(false);
        gf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) gf.getUI()).setNorthPane(null);
        

        jDesktopPane2.add(gf);
        gf.setVisible(true);

        try {
            gf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                
            }
        });
        
    }
    
    private void openHomeFrame() {
        jDesktopPane2.removeAll();
        jDesktopPane2.repaint();

        HomeFrame phf = new HomeFrame(jDesktopPane2);

        phf.setClosable(false);
        phf.setResizable(false);
        phf.setMaximizable(false);
        phf.setIconifiable(false);
        phf.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) phf.getUI()).setNorthPane(null);
        
        jDesktopPane2.add(phf);
        phf.setVisible(true);

        try {
            phf.setMaximum(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCl;
    private javax.swing.JButton btnGraph;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMd;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnPt;
    private javax.swing.JButton btnRdv;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
