/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.MedcinDao;
import entities.Medcin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Medecins extends javax.swing.JInternalFrame {
    int id;
    DefaultTableModel model = null;
    MedcinDao dao = new MedcinDao();

    /**
     * Creates new form Medecins
     */
    public Medecins() {
        initComponents();
        loadMedcins();
    }
    
    private void loadMedcins() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Medcin m : dao.findAll()) {
            model.addRow(new Object[]{
                m.getId(),
                m.getNom(),
                m.getSpecialite(),
                m.getTelephone()
            });
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAjout = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSuppr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(21, 31, 40));

        btnAjout.setBackground(new java.awt.Color(237, 237, 237));
        btnAjout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAjout.setForeground(new java.awt.Color(198, 40, 40));
        btnAjout.setText("Ajouter");
        btnAjout.setBorderPainted(false);
        btnAjout.setContentAreaFilled(false);
        btnAjout.setFocusPainted(false);
        btnAjout.setOpaque(true);
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(198, 40, 40));
        btnModifier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(237, 237, 237));
        btnModifier.setText("Modifier");
        btnModifier.setBorderPainted(false);
        btnModifier.setContentAreaFilled(false);
        btnModifier.setFocusPainted(false);
        btnModifier.setOpaque(true);
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSuppr.setBackground(new java.awt.Color(237, 237, 237));
        btnSuppr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuppr.setForeground(new java.awt.Color(198, 40, 40));
        btnSuppr.setText("Supprimer");
        btnSuppr.setBorderPainted(false);
        btnSuppr.setContentAreaFilled(false);
        btnSuppr.setFocusPainted(false);
        btnSuppr.setOpaque(true);
        btnSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(237, 237, 237));
        jTable1.getTableHeader().setBackground(new java.awt.Color(237, 237, 237));
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 18));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 31, 40), 1, true));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Specialite", "Telephone"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(21, 31, 40));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(2);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(btnSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        // TODO add your handling code here:
        MedecinDialog dialog = new MedecinDialog((JFrame) SwingUtilities.getWindowAncestor(this), null);
        dialog.setVisible(true);

        loadMedcins();
    }//GEN-LAST:event_btnAjoutActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        Medcin selectedMedcin = dao.findById(id);
        if (selectedMedcin != null) {
            MedecinDialog dialog = new MedecinDialog((JFrame) SwingUtilities.getWindowAncestor(this), selectedMedcin);
            dialog.setVisible(true);

            loadMedcins();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a mededin first.");
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Etes vous sure de supprimer ce medecin?", 
            "Confirmer suppression", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Medcin m = dao.findById(id);
            if (m != null && dao.delete(m)) {
                JOptionPane.showMessageDialog(this, "Medecin supprimé.");
                loadMedcins();
            } else {
                JOptionPane.showMessageDialog(this, "Medcin pas supprimé.");
            }
        }
        
    }//GEN-LAST:event_btnSupprActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        id = (int) jTable1.getValueAt(selectedRow, 0);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSuppr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
