/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.MedcinDao;
import dao.PatientDao;
import dao.RDVDao;
import entities.Medcin;
import entities.Patient;
import entities.RDV;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Rdvs extends javax.swing.JInternalFrame {
    Patient selectedPatient;
    Medcin selectedMedcin;
    Date selectedDate;

    DefaultTableModel model = null;
    RDVDao rdao = new RDVDao();
    MedcinDao mdao = new MedcinDao();
    

    
    /**
     * Creates new form Rdvs
     */
    public Rdvs() {
        initComponents();
        loadRdvs();
        loadSpecialities();
    }
    
    private void loadRdvs(List<RDV> list) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (RDV r : list) {
            model.addRow(new Object[]{
                r.getPatient().getId(),
                r.getMedcin().getId(),
                r.getDateRDV(),
                r.getActe(),
                r.getTarif(),
                r.getPatient().getNom(),
                r.getMedcin().getNom()
            });
        }
        
        calculateRevenue(list);
    }
    
    private void loadRdvs() {
        loadRdvs(rdao.findAll());
    }
    
    private void loadSpecialities() {
        comboSpec.removeAllItems();
        comboSpec.addItem("Tous");

        
        for (String s : mdao.findAllSpecialties()) {
            comboSpec.addItem(s);
        }
    }
    
    private void calculateRevenue(List<RDV> list) {
        double total = 0;
        for (RDV r : list) {
            total += r.getTarif();
        }
        txtTarif.setText("Le total des recettes est: " + (int) total + " DH"); // casting to int removes decimals
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAjout = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSuppr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtTarif = new javax.swing.JLabel();
        txtdateFrom = new com.toedter.calendar.JDateChooser();
        txtdateTo = new com.toedter.calendar.JDateChooser();
        comboSpec = new javax.swing.JComboBox();
        btnReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(21, 31, 40));

        btnAjout.setBackground(new java.awt.Color(237, 237, 237));
        btnAjout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAjout.setForeground(new java.awt.Color(198, 40, 40));
        btnAjout.setText("Ajouter");
        btnAjout.setBorderPainted(false);
        btnAjout.setContentAreaFilled(false);
        btnAjout.setFocusPainted(false);
        btnAjout.setOpaque(true);
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(198, 40, 40));
        btnModifier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(237, 237, 237));
        btnModifier.setText("Modifier");
        btnModifier.setBorderPainted(false);
        btnModifier.setContentAreaFilled(false);
        btnModifier.setFocusPainted(false);
        btnModifier.setOpaque(true);
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSuppr.setBackground(new java.awt.Color(237, 237, 237));
        btnSuppr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuppr.setForeground(new java.awt.Color(198, 40, 40));
        btnSuppr.setText("Supprimer");
        btnSuppr.setBorderPainted(false);
        btnSuppr.setContentAreaFilled(false);
        btnSuppr.setFocusPainted(false);
        btnSuppr.setOpaque(true);
        btnSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(40, 31, 21));

        jTable1.setBackground(new java.awt.Color(237, 237, 237));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 31, 40), 1, true));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PtId", "MdId", "Date", "Acte", "Tarif", "Patient", "Medecin"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(21, 31, 40));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(2);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        txtTarif.setBackground(new java.awt.Color(21, 31, 40));
        txtTarif.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtTarif.setForeground(new java.awt.Color(237, 237, 237));
        txtTarif.setText("Tarifs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(txtTarif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTarif, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        txtdateFrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtdateTo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        comboSpec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboSpec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnReset.setBackground(new java.awt.Color(198, 40, 40));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(237, 237, 237));
        btnReset.setText("Réinitialiser");
        btnReset.setBorderPainted(false);
        btnReset.setContentAreaFilled(false);
        btnReset.setFocusPainted(false);
        btnReset.setOpaque(true);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(21, 31, 40));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 237, 237));
        jLabel5.setText("Filtrer de");

        jLabel6.setBackground(new java.awt.Color(21, 31, 40));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 237, 237));
        jLabel6.setText("à");

        jLabel7.setBackground(new java.awt.Color(21, 31, 40));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(237, 237, 237));
        jLabel7.setText("par specialité");

        btnSearch.setBackground(new java.awt.Color(198, 40, 40));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(237, 237, 237));
        btnSearch.setText("Rechercher");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setFocusPainted(false);
        btnSearch.setOpaque(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        // TODO add your handling code here:
        RdvDialog dialog = new RdvDialog((JFrame) SwingUtilities.getWindowAncestor(this), null);
        dialog.setVisible(true);

        loadRdvs();
    }//GEN-LAST:event_btnAjoutActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        if (selectedPatient != null && selectedMedcin != null && selectedDate != null) {
        RDV selectedRdv = rdao.findByKey(selectedPatient.getId(), selectedMedcin.getId(), selectedDate);
        if (selectedRdv != null) {
            RdvDialog dialog = new RdvDialog((JFrame) SwingUtilities.getWindowAncestor(this), selectedRdv);
            dialog.setVisible(true);
            loadRdvs();
        }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a Rendez-vous first.");
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprActionPerformed
        // TODO add your handling code here:
        if (selectedPatient != null && selectedMedcin != null && selectedDate != null) {
        int confirm = JOptionPane.showConfirmDialog(this,
            "Etes vous sure de supprimer ce Rendez-vous?",
            "Confirmer suppression", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            RDV r = rdao.findByKey(selectedPatient.getId(), selectedMedcin.getId(), selectedDate);
            if (r != null && rdao.delete(r)) {
                JOptionPane.showMessageDialog(this, "Rendez-vous supprimé.");
                loadRdvs(); // refresh table
            } else {
                JOptionPane.showMessageDialog(this, "Rendez-vous pas supprimé.");
            }
        }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a Rendez-vous first.");
        }

    }//GEN-LAST:event_btnSupprActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        int patientId = (int) jTable1.getValueAt(selectedRow, 0);
        int medcinId = (int) jTable1.getValueAt(selectedRow, 1);
        selectedDate = (Date) jTable1.getValueAt(selectedRow, 2);
        
        selectedPatient = new PatientDao().findById(patientId);
        selectedMedcin = new MedcinDao().findById(medcinId);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtdateFrom.setDate(null);
        txtdateTo.setDate(null);
        comboSpec.setSelectedIndex(0); // "All"
        loadRdvs(rdao.findAll());
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Date dateFrom = txtdateFrom.getDate();
        Date dateTo   = txtdateTo.getDate();

        String specialite = comboSpec.getSelectedItem().equals("Tous")
                ? null
                : comboSpec.getSelectedItem().toString();

        List<RDV> result = rdao.search(dateFrom, dateTo, specialite);
        loadRdvs(result);

    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSuppr;
    private javax.swing.JComboBox comboSpec;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtTarif;
    private com.toedter.calendar.JDateChooser txtdateFrom;
    private com.toedter.calendar.JDateChooser txtdateTo;
    // End of variables declaration//GEN-END:variables
}
